### ISSUE TITLE
Hello from tagwiki

### ISSUE THREAD

**Issue by dpc** [xvxx/deadwiki#3]
I've just seen https://www.reddit.com/r/rust/comments/impz8p/cratedigging_episode_3_deadwiki/ , and when I was looking at the description, it looks awfully lot like my https://github.com/dpc/tagwiki , so decided to say hello.

For me personally the tag handling (everything is addressed by the tags) was the important part, and that's why I was hacking on tagwiki.

I'm actually not doing any coding in my free time in the last few months due to COVID and personal reasons, and I don't expect it to change anytime soon. But maybe you could use it for inspiration or something. Anyway. Happy hacking!

**Comment by xvxx** [comment]
Hello there, and thank you for saying hi! TagWiki is very cool!

The timing of your comment is serendipitous for me, because just the other day I was thinking about something similar (but less thought out). Like, "What if I could build dynamic wiki 'pages' out of multiple 'notes' that are quick to create? And then use tags to simulate a hierarchy, so wiki pages can live in multiple fake directory trees at once?"

And then et voila, here you are!

I am certainly going to be taking inspiration from this! I especially love the keyboard shortcuts, deadwiki has a few but none for link navigating. Thank you for sharing.

**Comment by xvxx** [comment]
I should also say thanks for sharing that Reddit link, that is super cool and a bit shocking! I've just been writing this for me and using it to experiment with my lil web framework, so seeing it get featured like that was a real surprise!
